pixel/urls.py
from django.conf.urls import url
from django.urls import path
from django.views.generic import TemplateView
from . import views
from .views import save_image, play_song, stop_song, stats

app_name = "pixel"

urlpatterns = [
   url(r'^image/',TemplateView.as_view(template_name = 'pixel/profile.html'),name='image'),
   url(r'^saved/',save_image, name='saved'),
   url(r'^play/',play_song, name='play'),
   url(r'^stop/',stop_song, name='stop'),
   url(r'^stats/',stats, name='stats')
]

pixel_music/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('pixel/', include('pixel.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

pixel/models.py
from __future__ import unicode_literals
from django.db import models

class Image(models.Model):
   name = models.CharField(max_length=255)
   picture = models.ImageField()

   class Meta:
      db_table = "image"

class Metrics(models.Model):
   pixels = models.IntegerField()
   processing_time = models.FloatField()

pixel/forms.py
from django import forms
from pixel.image_to_music import file_size

class ImageForm(forms.Form):
   name = forms.CharField(max_length=255, required=False)
   picture = forms.ImageField(validators=[file_size])

pixel/views.py
import time
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, render, render_to_response
from .image_to_music import get_image_data, pixels_to_midi
from .midi_player import load_file, play, stop
from django.urls import reverse
from django.views import generic
from django.views.decorators.csrf import csrf_exempt
from .models import Image, Metrics
from .forms import ImageForm


@csrf_exempt
def stats(request):
    metrics = Metrics.objects.all()
    average_pixels = sum([x.pixels for x in metrics])/len(metrics)
    average_time = sum([x.processing_time for x in metrics])/len(metrics)
    return render_to_response('pixel/profile.html', {'saved': True,
                              'average_pixels': average_pixels,
                              'average_time': average_time})

@csrf_exempt
def play_song(request):
    play()
    return render_to_response('pixel/profile.html', {'saved':True})


@csrf_exempt
def stop_song(request):
    stop()
    return render_to_response('pixel/profile.html', {'saved':True})


@csrf_exempt
def save_image(request):
    form = ImageForm(request.POST or None, request.FILES or None)
    if form.is_valid():
       start = time.time()
       image = Image()
       image.name = form.cleaned_data["name"]
       image.picture = form.cleaned_data["picture"]
       image.save()
       saved = True
       midi_file_name = image.name[:10]+".mid"
       pixels = get_image_data(image.picture)
       num_pixels = pixels_to_midi(pixels, midi_file_name)
       load_file(midi_file_name)
       metrics = Metrics(processing_time=time.time() - start,
                         pixels=num_pixels)
       metrics.save()
       return render_to_response('pixel/profile.html', {'saved':True,
                                 'song':True,'image':{'name':image.name}})
    else:
       return render_to_response('pixel/profile.html',{'form': form})

pixel/templates/pixel/profile.html
<html>
   <head>
     {% load staticfiles %}
     <link rel='stylesheet' href="{% static 'styles.css' %}">
   </head>
   <body>
      <h1 class="tangerine">pixel_music</h1>
      <p class="tangerine">Upload a picture up to 100KB and see what it would
        sound like if you played the pixels like sheet music</p>
      <form name = "form" enctype = "multipart/form-data"
         action = "{% url "pixel:saved" %}" method ="POST">{% csrf_token %}
         <input type="file" placeholder="Picture" name ="picture"/>
         <br><br>
         <button class="button-style" type="submit" value="Upload">
            <strong>Upload</strong>
         </button>
      </form>
      <div>
        {% if form.errors %}
          {% for field in form %}
            {% for error in field.errors %}
              <div class="alert alert-danger">
                 <strong>{{ error|escape }}</strong>
              </div>
            {% endfor %}
          {% endfor %}
          {% for error in form.non_field_errors %}
            <div class="alert alert-danger">
                <strong>{{ error|escape }}</strong>
            </div>
          {% endfor %}
        {% endif %}
      </div>
      <div>
        {% if song %}
          <p class="tangerine">Ready!</p>
        {% endif %}
        <form name = "form" enctype = "multipart/form-data" style="display:inline-block;"
           action = "{% url "pixel:play" %}" method ="POST">{% csrf_token %}
          <button class="button-style" type="submit" value="Play">
             <strong>Play</strong>
          </button>
        </form>
        <form name = "form" enctype = "multipart/form-data" style="display:inline-block;"
           action = "{% url "pixel:stop" %}" method ="POST">{% csrf_token %}
          <button class="button-style" type="submit" value="Stop">
             <strong>Stop</strong>
          </button>
        </form>
        <form name = "form" enctype = "multipart/form-data"
           action = "{% url "pixel:stats" %}" method ="POST">{% csrf_token %}
          <button class="button-style" style="width:160px;" type="submit" value="Stats">
             <strong>Click here if you like stats?</strong>
          </button>
        </form>
        {% if average_pixels and average_time %}
          <p class="tangerine">Average number of pixels in images uploaded here:
            <span class="powder">{{average_pixels}}</span></p>
          <p class="tangerine">Average image processing time in seconds:
            <span class="powder">{{average_time}}</span></p>
        {% endif %}
      </div>
   </body>
</html>

pixel/templates/pixel/saved.html
<html>
   <body>

      {% if saved %}
         <strong>Your image was saved.</strong>
      {% endif %}

      {% if not saved %}
         <strong>Your image was not saved.</strong>
      {% endif %}

   </body>
</html>